### PR TITLE
3D Print / Animation

### PR DESCRIPTION
**Pull request by aariverock**
- Fix pin placement for 3d print
- Add VRay parametric animation feature

### CODE REVIEW

**Comment by armantorkzaban** [comment]
Great work. I am thinking about publishing the videos. WDYT?

**Comment by aariverock** [comment]
Happy to hear that.
Well I think it depends on our marketing strategy according to the
project's open source nature which is not clear to me.

**Comment by armantorkzaban** [comment]
Maybe first the text about the whole project and then the rest. I will come up with a timeline and let you know.

**Comment by aariverock** [comment]
Ok, sounds good.

**Pull request merged**
